config/routes.rb
Rails.application.routes.draw do
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :items do
    resources :comments  
  end
  
  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :item
end

app/models/item.rb
class Item < ApplicationRecord
    has_many :comments, dependent: :delete_all, dependent: :destroy
    has_one_attached :image1
    has_one_attached :image2
    has_one_attached :image3
end

app/models/user.rb
class User < ApplicationRecord
    def self.from_omniauth(auth)
        where(provider: auth.provider, uid: auth.uid).first_or_initialize.tap do |user|
            user.provider = auth.provider
            user.uid = auth.uid
            user.name = auth.info.name
            user.oauth_token = auth.credentials.token
            user.oauth_expires_at = Time.at(auth.credentials.expires_at)
            user.save!
        end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user
    
    def current_user
        @current_user ||= User.find(session[:user_id]) if session[:user_id]  
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def create
        @item = Item.find(params[:item_id])
        @comment = @item.comments.create(comments_params)
        redirect_to item_path(@item)
    end
    
    def destroy
        @item = Item.find(params[:item_id])
        @comment = @item.comments.find(params[:id])
        @comment.destroy
        redirect_to item_path(@item)
    end
    
    private
        def comments_params
            params.require(:comment).permit(:body)  
        end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
    
    def index
        
       @items = Item.all

    end

    
    def show

        @item = Item.find(params[:id])

    end
    
    
    def new

        @item = Item.new

    end

    

    def create

        @item = Item.new(item_params)
        
        if @item.save 

            redirect_to @item 

        else 

            render 'new' 

        end

    end


    
    def edit

        @item = Item.find(params[:id])

    end

    

    def update

        @item = Item.find(params[:id])

        
        if @item.update(item_params)

            redirect_to @item

        else

            render 'edit'

        end

    end

    

    def destroy  

        @item = Item.find(params[:id]) 

        @item.destroy

        
        redirect_to items_path 

    end 

end


private

    def item_params

        params.require(:item).permit(:title1, :title2, :title3, :text1, :text2, :text3, :date, :image1, :image2, :image3)

    end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.from_omniauth(request.env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to root_path
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/comments/_comment.html.erb
<p>
    <strong>Note:</strong>
    <%= comment.body %>
</p>

<p>
    <%= link_to 'Delete Comment', [comment.item, comment],
                method: :delete,
                class: "create_new_item",
                data: { confirm: 'Are you sure' } %>
</p>

<br><br>

app/views/comments/_form.html.erb
<%= form_for([@item, @item.comments.build]) do |f| %>
    <p>
        <%= f.label :Extra_Notes %><br>
        <%= f.text_field :body %>
    </p>
    
    <p>
        <%= f.submit %>
    </p>
<% end %>

app/views/items/edit.html.erb
<body class="gray">
  <h1 class="listing">Edit Meal Item Listing</h1>
  
  <%= link_to 'Back', items_path, class: "create_new_item"%>
  
  <%= form_for :item, url: item_path(@item), method: :patch do |f| %>
   
    <% if @item.errors.any? %>
        <div id="error_explanation">
          <h2>
            <%= pluralize(@item.errors.count, "error") %> prohibited
            this article from being saved:
          </h2>
          <ul>
            <% @item.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
  
      <p>
        <%= f.label :date %><br>
        <%= f.date_select :date,
          {
          use_month_numbers: false,
          start_year: 2019,
          order: [:month, :day, :year],
          prompt: { month: 'Select month', day: 'Select day', year: 'Select year' }
          },
          
          {:class => "date_select"}
        %>
      </p>
      
      <div class="row">
        <div class="column2">
          <h2>Breakfast</h2>
          <p>
            <%= f.label :image, required: true %><br>
            <%= f.file_field :image1 %>
          </p>
          
          <p>
            <%= f.label :food %><br>
            <%= f.text_field :title1 %>
          </p>
          
          <p>
            <%= f.label :description %><br>
            <%= f.text_area :text1 %>
          </p>
        </div>
        
        <div class="column2">
          <h2>Lunch</h2>
          <p>
            <%= f.label :image, required: true %><br>
            <%= f.file_field :image2 %>
          </p>
          
          <p>
            <%= f.label :food %><br>
            <%= f.text_field :title2 %>
          </p>
          
          <p>
            <%= f.label :description %><br>
            <%= f.text_area :text2 %>
          </p>
        </div>
        
        <div class="column2">
          <h2>Dinner</h2>
          <p>
            <%= f.label :image, required: true %><br>
            <%= f.file_field :image3 %>
          </p>
          
          <p>
            <%= f.label :food %><br>
            <%= f.text_field :title3 %>
          </p>
          
          <p>
            <%= f.label :description %><br>
            <%= f.text_area :text3 %>
          </p>
        </div>
      </div>
     
      <p>
        <%= f.submit %>
      </p>
  <% end %>
</body>

app/views/items/index.html.erb
<body class="gray" id="list_page">
  <h1 class="listing">Listing items</h1>
  <%= link_to 'Add new item', new_item_path, class: "create_new_item" %>
  <%= link_to 'Home', root_path, class: "create_new_item" %>
   
  <div class="tablediv">
    <table>
      <tr>
        <th class="header">Date</th>
        <th class="header">Breakfast</th>
        <th class="header">Lunch</th>
        <th class="header">Dinner</th>
      </tr>
      
      <div id="table">
        <% @items.each do |item| %>
          <tr>
            <td class="column nums"><%= item.date %></td>
            <td class="column nums"><%= item.title1 %></td>
            <td class="column nums"><%= item.title2 %></td>
            <td class="column nums"><%= item.title3 %></td>
            <td><%= link_to 'Show', item_path(item), class: "create_new_item" %></td>
            <td><%= link_to 'Edit', edit_item_path(item), class: "create_new_item" %></td>
            <td><%= link_to 'Destroy',
                                      item_path(item),
                                      method: :delete,
                                      class: "create_new_item",
                                      data: { confirm: 'Are you sure?' } %></td>
            
          </tr>
        <% end %>
      </div>
    </table>
  </div>
</body>

app/views/items/new.html.erb
<body class="gray">
  <h1 class="listing">New Meal Item</h1> 
  
  <%= link_to 'Home', root_path, class: "create_new_item" %>
  <%= link_to 'List Items', items_path, class: "create_new_item" %>
  
  <%= form_for :item, url: items_path do |f| %>
  
    <% if @item.errors.any? %>
        <div id="error_explanation">
          <h2>
            <%= pluralize(@item.errors.count, "error") %> prohibited
            this article from being saved:
          </h2>
          <ul>
            <% @item.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
    
    <p>
      <%= f.label :date %><br>
      <%= f.date_select :date,
        {
        use_month_numbers: false,
        start_year: 2019,
        order: [:month, :day, :year],
        prompt: { month: 'Select month', day: 'Select day', year: 'Select year' }
        },
        
        {:class => "date_select"}
      %>
    </p>
    
    <div class="row">
      <div class="column2">
        <h2>Breakfast</h2>
        <p>
          <%= f.label :image, required: true %><br>
          <%= f.file_field :image1 %>
        </p>
        
        <p>
          <%= f.label :food %><br>
          <%= f.text_field :title1 %>
        </p>
        
        <p>
          <%= f.label :description %><br>
          <%= f.text_area :text1 %>
        </p>
      </div>
      
      <div class="column2">
        <h2>Lunch</h2>
        <p>
          <%= f.label :image, required: true %><br>
          <%= f.file_field :image2 %>
        </p>
        
        <p>
          <%= f.label :food %><br>
          <%= f.text_field :title2 %>
        </p>
        
        <p>
          <%= f.label :description %><br>
          <%= f.text_area :text2 %>
        </p>
      </div>
      
      <div class="column2">
        <h2>Dinner</h2>
        <p>
          <%= f.label :image, required: true %><br>
          <%= f.file_field :image3 %>
        </p>
        
        <p>
          <%= f.label :food %><br>
          <%= f.text_field :title3 %>
        </p>
        
        <p>
          <%= f.label :description %><br>
          <%= f.text_area :text3 %>
        </p>
      </div>
    </div>
   
    <p>
      <%= f.submit %>
    </p>
  <% end %>
</body>

app/views/items/show.html.erb
<body class="gray">
    <br>
    <%= link_to 'Home', root_path, class: "create_new_item" %>
    <%= link_to 'Add new item', new_item_path, class: "create_new_item" %>
    <%= link_to 'Item List', items_path, class: "create_new_item" %>
    
    
    
    
    <div class="row">
        <div class="column2">
            <h2>Breakfast</h2>
            <p style="width:400px; height:auto">
            <%= image_tag(@item.image1, style: "width: 400px") %>
            </p>
            
            <p>
                <strong class="title_text">Date:</strong>
                <%= @item.date %>
            </p>
            
            <p>
                <strong class="title_text">Food:</strong>
                <%= @item.title1 %>
            </p>
            
            <p>
                <strong class="title_text">Description:</strong>
                <%= @item.text1 %>
            </p>
        </div>
        
        <div class="column2">
            <h2>Lunch</h2>
            <p style="width:400px; height:auto">
            <%= image_tag(@item.image2, style: "width: 400px") %>
            </p>
            
            <p>
                <strong class="title_text">Date:</strong>
                <%= @item.date %>
            </p>
            
            <p>
                <strong class="title_text">Food:</strong>
                <%= @item.title2 %>
            </p>
            
            <p>
                <strong class="title_text">Description:</strong>
                <%= @item.text2 %>
            </p>
        </div>
        
        <div class="column2">
            <h2>Dinner</h2>
            <p style="width:400px; height:auto">
            <%= image_tag(@item.image3, style: "width: 400px")%>
            </p>
            
            <p>
                <strong class="title_text">Date:</strong>
                <%= @item.date %>
            </p>
            
            <p>
                <strong class="title_text">Food:</strong>
                <%= @item.title3 %>
            </p>
            
            <p>
                <strong class="title_text">Description:</strong>
                <%= @item.text3 %>
            </p>
        </div>
    </div>
    
    <br>
    
    <h2>Comments</h2>
    <%= render @item.comments %>
    
    <br>
    
    <h2>Add a commment:</h2>
    <%= render 'comments/form' %>
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MealTracker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div>
      <% if current_user %>
        <span class="googlesign">Signed in as <strong><%= current_user.name %></strong></span>!
        <%= link_to "Sign out", signout_path, id: "sign_out", class: "create_new_item2"%>
      <% else %>
        <%= link_to "Sign in with Google", "/auth/google_oauth2", id: "sign_in", class: "create_new_item2" %>
      <% end %>
    </div>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<body id="image">
    <div class="topnav">
      <h1>Meal Tracker</h1>
    </div>
    <div class="welcome_container">
        
        <h1 id="wel_meal">Welcome to the Meal Tracker!</h1>
        
        <br>
        <%= link_to 'Create New Item', new_item_path, class: "create_new_item" %>
        
        <br><br><br>
        <%= link_to 'Current Items', {controller: 'items'}, class: "create_new_item" %>
        
    </div>
</body>